import Head from 'next/head'
import { useUser } from '../lib/hooks'
import clientPromise from '../lib/mongodb'
import { Inter } from '@next/font/google'
import { InferGetServerSidePropsType } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import {motion,AnimatePresence, delay} from "framer-motion"

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(context: any) {
  try {
    await clientPromise

    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default function Home({
  isConnected,
}: InferGetServerSidePropsType<typeof getServerSideProps> ) { 
  const user = useUser()
  return (
    <>
      <Head >
        <title>Student Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <img className="absolute top-0 bottom-0 z-10 h-[100%] w-[100%] opacity-90 object-cover  "
        src="/homebg2.jpg"
        alt=""
      />


      
        {/* <div className='z-40 relative'> */}
          <div  className='mx-auto z-40 relative '>
      <header  className="text-gray-600 body-font bg-black opacity-80">
  <div  className="container mx-auto flex flex-wrap p-4 flex-col md:flex-row items-center ">
    <a  className="flex title-font font-medium items-center text-white mb-4 md:mb-0">
      
      <span  className="ml-3 text-xl">CVR COE</span>
    </a>
    <nav  className="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center text-white">
      <a  className="mr-5  hover:font-semibold">HOME</a>
      <a  className="mr-5 hover:font-semibold">ABOUT US</a>
      <a  className="mr-5 hover:font-semibold">CONTACT US</a>
      <a  className="mr-5 hover:font-semibold">FAQ</a>
    </nav>
    <Link href={"/login"} className="inline-flex items-center bg-yellow-600 text-white border-0 py-1 px-3 focus:outline-none hover:bg-yellow-700 rounded text-base mt-4 mx-4 md:mt-0">LOGIN
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"  className="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </Link>
    <Link href={"/signup"}  className="inline-flex items-center bg-yellow-600 text-white border-0 py-1 px-3 focus:outline-none mx-4 hover:bg-yellow-700 rounded text-base mt-4 md:mt-0">SIGN UP
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"  className="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </Link>
  </div>
</header>
      </div>

      <motion.div className=' text-white z-40 relative mx-auto mt-44 bg-black h-[25%] w-[50%] flex flex-col justify-center align-middle rounded-xl '
      initial={{y:25,opacity:0}}
      animate={{y:0,opacity:1}}
      transition={{
        duration:0.75,
        delay:0.2
      }}
      > 
          <p className='text-4xl text-center font-extrabold'>BETTER <span className='text-yellow-600'>EDUCATION</span> FOR </p>
          <p className='text-4xl text-center my-1 font-extrabold'>AMAZING WORLD</p>
      </motion.div>
   
      <div className=' z-40 relative mx-auto flex h-[25%] justify-center '>
        
        <motion.div className='bg-yellow-600 rounded-b-2xl  w-[15%] '
        initial={{y:-10,opacity:0}}
        animate={{y:0,opacity:1}}
        transition={{
          duration:0.75,
          delay:0.2
        }}>
          <img src="/book2.gif" alt="" className='relative h-24 top-[-50px]  left-[75px] rounded-full' />
          <p className=' text-2xl font-bold relative  my-auto mr-5 mx-16'>Academics</p>
        </motion.div>
        <motion.div className='bg-gray-200 rounded-2xl  w-[15%] mx-4'
        initial={{y:-10,opacity:0}}
        animate={{y:0,opacity:1}}
        transition={{
          duration:0.75,
          delay:0.2
        }}>
        <img src="/event.gif" alt="" className='relative h-24 top-[-50px] left-[75px] rounded-full' />
        <p className=' text-2xl font-bold relative  my-auto mr-5 mx-[45px] text-center'>Events</p>

        </motion.div>
        <motion.div className='bg-yellow-600  rounded-b-2xl  w-[15%]'
        initial={{y:-10,opacity:0}}
        animate={{y:0,opacity:1}}
        transition={{
          duration:0.75,
          delay:0.2
        }}>
        <img src="/medal.gif" alt="" className='relative h-24 top-[-50px] left-[75px] rounded-full' />
        <p className=' text-2xl font-bold relative  my-auto mr-5 mx-[90px] '>Sports</p>

        </motion.div>
      </div>
        {/* </div> */}
      {/* )} */}
      
      
    </>
  )
}
